import '../public/globals.css'
import { FooterComponents } from './components/footer/footerComponents'
import { HeaderComponents } from './components/header/headerComponents'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter( { subsets: ['latin'] } )

export const metadata: Metadata = {
  title: 'Avo Store',
  description: 'Generated by create next app',
}

export default function RootLayout( {
  children,
}: {
  children: React.ReactNode
} ) {
  return (
    <html lang="en">
      <body className="">
        <HeaderComponents />
        {children}
        {/* <FooterComponents /> */}
      </body>
    </html>
  )
}
